name: Bug report
description: Report something that is broken or incorrect
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Before you post this issue, please check the documentation:

        - [PHoeNIx pipeline wiki documentation](https://github.com/CDCgov/phoenix/wiki)

  - type: textarea
    id: description
    attributes:
      label: Description of the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: command_used
    attributes:
      label: Command used and terminal output
      description: Steps to reproduce the behaviour. Please paste the command you used to launch the pipeline and the output from your terminal. If applicable, add screenshots to help explain your problem.
      render: console
      placeholder: |
        $ nextflow run ...

        Some output where something broke

  - type: textarea
    id: files
    attributes:
      label: Relevant files
      description: |
        Please drag and drop the relevant files here. Create a `.zip` archive if the extension is not allowed.
        Your verbose log file `.nextflow.log` is often useful _(this is a hidden file in the directory where you launched the pipeline)_ as well as custom Nextflow configuration files. 
        Additionally, the .command.err, .command.out, .command.sh files associated with the run/process that failed would be helpful. These files are found in <directory you ran pipeline from>/work/XX/xxxxxxxxxxxxxx here the x and X are a random string of letters/numbers associated with the process. 
        As the pipeline runs on CLI you will see the beginning of these strings to the left of the process that is running. 

  - type: textarea
    id: system
    attributes:
      label: System information
      description: |
        * Nextflow version _(eg. 22.10.1)_
        * Hardware _(eg. HPC, Desktop, Cloud)_
        * Executor _(eg. slurm, local, awsbatch)_
        * Container engine: _(e.g. Docker, Singularity, Conda, Podman, Shifter or Charliecloud)_
        * OS _(eg. CentOS Linux, macOS, Linux Mint)_
        * Version of phylophoenix _(eg. 1.1, 1.5, 1.8.2)_
