FROM mambaorg/micromamba:1.4.0
#USER root

# for easy upgrade later. ARG variables only persist during image build time
ARG NEXTFLOW="22.04.5"

# metadata
LABEL base.image="mambaorg/micromamba:1.4.0"
LABEL dockerfile.version="1"
LABEL software="nextflow"
LABEL software.version="22.04.5"
LABEL description="Nextflow container"
LABEL website="https://github.com/cdcgov/phoenix/"
LABEL license="https://github.com/CDCgov/phoenix/blob/main/LICENSE"
LABEL maintainer="Jill Hagey"
LABEL maintainer.email="jvhagey@gmail.com"

RUN micromamba create -n phoenix -y -c defaults -c bioconda -c conda-forge \
    nf-core \
    nextflow=22.04.5 && \
    micromamba clean -a -y

ENV PATH=/opt/conda/envs/phoenix/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin