# base image
FROM ubuntu:jammy

# for easy upgrade later. ARG variables only persist during image build time
ARG NT_VER="1.0.1"

# metadata
LABEL base.image="ubuntu:jammy"
LABEL dockerfile.version="2"
LABEL software="NewType"
LABEL software.version="v1.0.1"
LABEL description="Next-Generation based wgMLST typing and PCR-based Ribotyping Equivalents"
LABEL website=""
LABEL license="Apache 2.0"
LABEL author="Jill Hagey"
LABEL maintainer.email="qpk9@cdc.gov"
LABEL authors="Peng Qi"
LABEL authors.email="uom8@cdc.gov"

# prevents having to enter commands during apt-get install
ENV DEBIAN_FRONTEND=noninteractive

# install dependencies (pigz needed for nf-core modules, bc and rsync needed for post gamma steps in PHoeNIx)
RUN apt-get update && apt-get -y --no-install-recommends install \
    python3 \
    python3-pip \
    python-is-python3 && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/*

#install biopython
RUN pip3 install \
    argparse \
    pandas==2.1.1 \
    numpy==1.26.1 \
    xgboost==2.0.1 \
    joblib==1.3.2 \
    scikit-learn==1.3.2

ENV PATH="${PATH}:/usr/bin/python:/usr/bin/python3:/data/" LC_ALL=C

#set working directory so its easier to find the db
WORKDIR /data

#remove db and add custom mlst db
COPY cdiff-rtprediction/ /data
