FROM mambaorg/micromamba:2.0.5 as micromamba

# metadata
LABEL base.image="mambaorg/micromamba:2.0.5"
LABEL dockerfile.version="1"
LABEL software="phoenix"
LABEL software.version="2.2.0"
LABEL description="PHoeNIx: A short-read pipeline for healthcare-associated and antimicrobial resistant pathogens"
LABEL website="https://github.com/cdcgov/phoenix/"
LABEL license="https://github.com/CDCgov/phoenix/blob/main/LICENSE"
LABEL maintainer="Jill Hagey"
LABEL maintainer.email="jvhagey@gmail.com"

#install conda in the base environment
#RUN conda install mamba -n base -c conda-forge
#RUN conda config --add channels defaults && \
#conda config --add channels bioconda && \
#conda config --add channels conda-forge

# creating base environment
RUN micromamba create -n phoenix -c defaults -c bioconda -c conda-forge \
    conda-forge::python  \
    conda-forge::biopython \
    anaconda::pandas=1.3.5 \
    anaconda::openpyxl \
    conda-forge::rsync \
    conda-forge::xlsxwriter \
    conda-forge::bc \
    conda-forge::wget \
    conda-forge::ca-certificates \
    conda-forge::procps-ng \
    conda-forge::coreutils \
    conda-forge::openssl \
    conda-forge::gsutil \
    conda-forge::pigz \
    anaconda::git=2.40.1 \
    anaconda::graphviz \
    conda-forge::libcurl \
    # need this for mash: error while loading shared libraries: libgsl.so.25: https://github.com/ParBLiSS/FastANI/issues/96
    conda-forge::gsl=2.7=he838d99_0 \
    # you need this not the Jetbrains versio of java https://github.com/nextflow-io/nextflow/issues/2841
    conda-forge::openjdk \
    #bioconda::bbmap=39.13 \
    bioconda::multiqc=1.14 \
    bioconda::fastp=0.24.0 \
    bioconda::mash=2.3 \
    bioconda::mlst=2.23.0 \
    bioconda::fastqc=0.12.1 \
    bioconda::gamma=2.2 \
    bioconda::sra-tools=3.0.9 \
    bioconda::fastani=1.34 \
    bioconda::entrez-direct=16.2 \
    bioconda::kraken2=2.1.3 \
    bioconda::spades=4.0.0 \
    bioconda::krona=2.8.1 \
    bioconda::shigapass=1.5.0 \
    #bioconda::prokka=1.14.5 \
    #bioconda::quast=5.2.0 \
    bioconda::nextflow=24.10.4 && \
    micromamba clean -a -y
    #&& echo "source activate phoenix" >> ~/.bashrc

RUN micromamba create -n bbmap -c conda-forge bioconda::bbmap=39.13 && micromamba clean -a -y
RUN micromamba create -n quast -c conda-forge bioconda::quast=5.3.0 && micromamba clean -a -y
RUN micromamba create -n prokka -c conda-forge bioconda::prokka=1.14.5 && micromamba clean -a -y
RUN micromamba create -n busco -c conda-forge -c bioconda busco=5.4.7 && micromamba clean -a -y
RUN micromamba create -n srst2 -c conda-forge bioconda::srst2==0.2.0 && micromamba clean -a -y
RUN micromamba create -n amrfinderplus -c conda-forge bioconda::ncbi-amrfinderplus=4.0.19 && micromamba clean -a -y

#RUN source ~/opt/conda/etc/profile.d/conda.sh
ENV PATH=/opt/conda/envs/phoenix/bin:/opt/conda/bin:/opt/conda/envs/env/bin:/opt/conda/envs/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
#PATH=/opt/conda/envs/srst2/bin:$PATH
#:/opt/conda/envs/amrfinderplus/bin:/opt/conda/envs/srst2/bin:/opt/conda/envs/quast/bin:/opt/conda/envs/busco/bin:\
#

# updating srst2 - srst2 hasn't had a new release since 2016, despite having bug fixes on the repo.
RUN pip install git+https://github.com/katholt/srst2.git@73f885f55c748644412ccbaacecf12a771d0cae9 --upgrade --target=/opt/conda/envs/srst2/lib/python2.7/site-packages

# Making edits to srst2 code to enable handling of () in ar gene names
RUN sed -i '1502s/.*/\t\t\t\tcommand = "grep \\""+allele+"\\" "+fasta\n\t\t\t\theader_string = os.popen(command)/' /opt/conda/envs/srst2/lib/python2.7/site-packages/srst2/srst2.py
# fixing bug - similar to patch found here https://github.com/bioconda/bioconda-recipes/blob/d4454836e2b5f834d6c5bc35eaa2b1f9ee5c7e8a/recipes/srst2/srst_sample_name_v0.2.0.patch
RUN sed -i '453s/.*/					sample_name = pileup_file[::-1].split("\.")[2]\.split("_")[0][::-1]\n\t\t\t\t\tconsensus_outfile\.write(">{0}\.{1} {2}\\n"\.format(allele, consensus_type, sample_name))/' /opt/conda/envs/srst2/lib/python2.7/site-packages/srst2/srst2.py

#setting up stuff for BUSCO
ENV AUGUSTUS_CONFIG_PATH=/opt/conda/envs/busco/config/

#remove db and add custom mlst db
RUN rm /opt/conda/envs/phoenix/db/scheme_species_map.tab && rm -r /opt/conda/envs/phoenix/db/pubmlst && rm -r /opt/conda/envs/phoenix/db/blast
COPY --chown=mambauser:mambauser db /opt/conda/envs/phoenix/db/
#change permissions of database files
RUN chmod 755 --recursive /opt/conda/envs/phoenix/db/*

#-e ENV_NAME=env2
#RUN micromamba shell init --shell bash