# base image
FROM ubuntu:jammy

# for easy upgrade later. ARG variables only persist during image build time
ARG PHX_VER="2.0.0"

# metadata
LABEL base.image="ubuntu:jammy"
LABEL dockerfile.version="2"
LABEL software="PhoeNIx"
LABEL software.version="v2.0.0"
LABEL description="Basic Linux for Running PHoeNIx bash scripts"
LABEL website="https://github.com/cdcgov/phoenix"
LABEL license="Apache 2.0"
LABEL maintainer="Jill Hagey"
LABEL maintainer.email="qpk9@cdc.gov"

# prevents having to enter commands during apt-get install
ENV DEBIAN_FRONTEND=noninteractive

# install dependencies (pigz needed for nf-core modules, bc and rsync needed for post gamma steps in PHoeNIx)
RUN apt-get update && apt-get -y --no-install-recommends install \
    ca-certificates \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    make \
    llvm \
    libncurses5-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libffi-dev \
    liblzma-dev \
    build-essential \
    bc \
    pigz \
    rsync \
    unzip \
    tar \
    gzip \
    curl \
    wget && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/*

# using pyenv to set up an environment for python v3.7.12 to match what is required for the terra container
RUN mkdir /pyenv && git clone https://github.com/pyenv/pyenv.git /pyenv
ENV PYENV_ROOT=/pyenv
RUN /pyenv/bin/pyenv install 3.7.12
RUN eval "$(/pyenv/bin/pyenv init -)" && /pyenv/bin/pyenv local 3.7.12
RUN /pyenv/bin/pyenv global 3.7.12

RUN apt-get update && apt-get -y --no-install-recommends install python3-pip

ENV PATH=/pyenv/bin:/pyenv/shims:${PATH}

#install biopython and other required modules
RUN pip3 install biopython \
    glob2 \
    argparse \
    unidecode \
    pandas \
    numpy \
    regex \
    times \
    xlsxwriter \
    cryptography==36.0.2 \
    pytest-shutil \
    openpyxl 
